### ISSUE TITLE
Wetter API begutachten und Funktion schreiben

### ISSUE THREAD

**Issue by kryptokommunist** [phucdev/weatherbot#4]
Was für Datenpunkte bekomme ich? Temperatur, Luftfeuchte, Wind/Regen/Sturm...

Funktion welche bei geg. Ort u. Zeit ein dictionary mit entsprechenden Werten zurückgibt!

**Comment by phucdev** [comment]
Ich habe alle Wetterdaten, die man von OpenWeatherMap bekommen kann in einem Dictionary namens weather_data gebündelt.

```
weather_data = {}
weather_data['clouds'] = w.get_clouds()
weather_data['temperature'] = w.get_temperature('celsius')
```

usw.
